fisa_django/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog_app'

urlpatterns = [
    # blog 앱 내부의 경로를 지정할 부분
    # path('', views.index), # localhost:8000/blog 경로, 경로를 호출하면 실행할 함수의 위치
    path('post-list', views.PostList.as_view(paginate_by=5), name = 'post_list'),
    path('', views.about_me, name='about_me'),
    path('<int:pk>', views.PostDetail.as_view(), name="revise"), # <자료형:필드명> 
    path('create-post/', views.PostCreate.as_view(), name="create"), # blog_app:create
    path('user-delete/', views.user_delete, name='user_delete'),
    # update는 이미 있는 글을 수정하므로 글번호가 필요합니다.
    path('edit-post/<int:pk>', views.PostUpdate.as_view(), name = 'update'),
    path('delete-post/<int:pk>', views.PostDelete.as_view(), name = 'delete'),
    
    # 겉운 tag를 가진 글끼리 게시판에 보여주기
    path('tag/<str:slug>', views.tag_posts, name="tag"),


    # 댓글 조회 -> post-detail.html 안에서 동작하도록
    # 댓글 작성
    path('<int:pk>/create-comment', views.create_comment, name = 'create_comment'),
    # 댓글 수정
    path('update-comment/<int:pk>', views.CommentUpdate.as_view(), name='update_comment'),
    # 댓글 삭제
    path('delete-comment/<int:pk>', views.delete_comment, name='delete_comment'),

    # 검색을 위한 주소
    path("search/<str:q>/", views.PostSearch.as_view(), name="search")
]

fisa_django/fisa_django/urls.py
from django.contrib import admin
from django.urls import path, include
# 이미지 업로드 필드를 위한 추가
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include('blog.urls')),  # locahost:8000/blog/실제blog/urls.py에 적힌 경로
    #path("account/", include('account.urls')),
    path("accounts/", include('allauth.urls')),
    path("", include('blog.urls')),
] + debug_toolbar_urls()
# django_project/urls.py에 추가
# python -m pip install Pillow



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fisa_django/blog/models.py
from django.db import models
from django.contrib.auth.models import User


# Tag table 작성 - pk는 자동 생성됨
class Tag(models.Model):
    tag_name = models.CharField(max_length=30, unique=True)
    # 짧은 라벨로서, 문자, 숫자, 밑줄 또는 하이픈만을 포함. 일반적으로 URL에 사용.  
    slug = models.SlugField(max_length=30, unique=True, allow_unicode=True)

    def __str__(self):
        return self.tag_name
    
    def get_absolute_url(self): 
        return f'/blog/tag/{self.slug}'


# Create your models here.
# models모듈의 Model 클래스를 상속받는 자식클래스 생성
# 게시글에 필요한 필드는 무엇무엇일까요
class Post(models.Model): 
    title = models.CharField(max_length=50)
    content = models.TextField()
		
	# django model 이 최초 저장(insert) 시에만 현재날짜(date.today()) 를 적용
    # 아예 값 자체가 지금 시간으로 입력되어 들어감(우리가 변경할 필요 없음)
    created_at = models.DateTimeField(auto_now_add=True) # now()
	# django model 이 save 될 때마다 현재날짜(date.today()) 로 갱신됨
    updated_at = models.DateTimeField(auto_now=True) 

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    
    # 외래키와 프라이머리키의 관계
    # CASCADE - User가 삭제되면 관련있는 Post 테이블의 모든 글이 삭제
    # SET_NULL - User가 삭제되면 관련있는 Post 테이블의 모든 글에 author 항목은 NULL로 바뀜
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    tag = models.ManyToManyField(Tag)
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)

    def __str__(self):
        return f'[[{self.pk}] {self.title}]'
		
    def get_absolute_url(self): 
        return f'/blog/{self.pk}'




class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)  # 하나의 포스트에 여러개의 댓글 관계
    author = models.ForeignKey(User, on_delete=models.CASCADE) # 여러 사람이 하나의 댓글창에 댓글 구현 가능
    content = models.TextField()
    
    # 아예 값 자체가 지금 시간으로 입력되어 들어감(우리가 변경할 필요 없음)
    created_at = models.DateTimeField(auto_now_add=True) # now()
	# django model 이 save 될 때마다 현재날짜(date.today()) 로 갱신됨
    updated_at = models.DateTimeField(auto_now=True) 

    def __str__(self):
        return f'[[{self.pk}] {self.content}]'
		
    def get_absolute_url(self): 
        return f'{self.post.get_absolute_url()}#comment-{self.pk}' # #을 단 이유 : html에서 ID 

fisa_django/blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm) :
    class Meta : # 추가적인 정보들을 달아서 보낼 때 사용하는 클래스    
        model = Comment
        fields = ['content']

fisa_django/blog/views.py
from typing import Any
from django.db.models.query import QuerySet, Q # 장고 ORM에서 쿼리문처럼 or and 조건을 좀 더 편하게 쓰게 만들어 놓은 클래스
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Post, Tag, Comment
from .forms import CommentForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.utils.text import slugify


from django.views.decorators.http import require_POST
from django.contrib.auth import logout as auth_logout 
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login # authenticate : 인가, login : 인증 담당
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.exceptions import PermissionDenied

from django.contrib import messages # 예외나 상황에 대한 메시지 처리
from django.contrib.auth.mixins import LoginRequiredMixin

# Mixin라는 부가 기능들을 확인하기 위해 다중상속으로 주 기능을 확장하는 별도의 클래스
# 주 기능을 가진 클래스 앞에 작성

class PostCreate(LoginRequiredMixin, CreateView) :
    model = Post
    fields = ["title", "content", "head_image", "file_upload"]

    # CreateView가 내장한 함수 - 오버라이딩
    # tag는 참조관계이므로 Tag 테이블에 등록된 태그만 쓸 수 있는 상황
    # 임의로 방문자가 form에 Tag를 달아서 보내도록 form_valid()에 결과를
    # 저장된 포스트로 돌아오도록
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_active):
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)

            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()   # 책; 독후감, 작가명

                tags_str = tags_str.replace(',', ';')
                tags_list = tags_str.split(';')

                for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(tag_name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tag.add(tag)

            return response

        else:
                return redirect('/blog/')

class PostList(ListView):   # post_list.html, post-list
    model = Post 
    # template_name = 'blog/index.html' 
    ordering = '-pk' 
    context_object_name = 'post_list'

class PostSearch(PostList) :
    def get_queryset(self) :
        q = self.kwargs['q']
        post_list = Post.objects.filter(Q(title__contains=q) | Q(content__contains=q) | Q(tag__tag_name__contains=q)).select_related('author')
        return post_list


def index(request): # 함수를 만들고, 그 함수를 도메인 주소 뒤에 달아서 호출하는 구조
    posts = Post.objects.all()
    return render(
        request,
        'blog/index.html', {
            'posts':posts, 'my_list': ["apple", "banana", "cherry"], 'my_text': "첫번째 줄 \n 두번째 줄", 'content' : '<img src="data/jjangu.jpg" / >'
        }
    )# 없는 index.html을 호출하고 있음

def about_me(request): # 함수를 만들고, 그 함수를 도메인 주소 뒤에 달아서 호출하는 구조
    return render(
        request,
        'blog/about_me.html'
    )

class PostDetail(DetailView): # 함수를 만들고, 그 함수를 도메인 주소 뒤에 달아서 호출하는 구조
    model = Post 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["now"] = '임의로 작성한 새로운 변수'
        context["comment_form"] = CommentForm
        print(context['now'])
        return context

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'head_image', 'file_upload']
    
    # 로그인한 상태에서 작성자(request.user) 가 object.author(Post.objects.get(pk=pk))과 일치하는지 확인 필요
    def dispatch(self, request, *args, **kwargs): # 방문자가 GET으로 요청했는데 POST로 요청했는지 확인하는 기능
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied # 권한 없는 사람이 글 수정하려 하면 403

    # author 필드는 당연히 이전에 글을 생성한 작성자로 채워져있고, 
    # LoginRequiredMixin으로 로그인한 유저 확인하므로 form_valid는 오버라이딩하지 않음
    # 태그에 여러개 보내면 겹치지 않는 것만 새로 성성하는 기능은 필요하므로 get_context_data를 오버라이딩
    def get_context_data(self, **kwargs):
        context = super(PostUpdate, self).get_context_data()
        if self.object.tag.exists():
            tags_str_list = list()
            for t in self.object.tag.all():
                tags_str_list.append(t.tag_name)
            context['tags_str_default'] = '; '.join(tags_str_list)

        return context

    # 포스트에 태그를 추가하려면 이미 데이터베이스에 저장된 pk를 부여받아서 수정해야 함, 
    # 그래서 form_valid()를 통해 결과를 response 변수에 임시 담아두고
    # 서로 저장된 포스트를 self.object로 저장함.
    def form_valid(self, form):
        response = super(PostUpdate, self).form_valid(form)
        self.object.tag.clear()

        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')
            tags_list = tags_str.split(';')

            for t in tags_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(tag_name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tag.add(tag)

        return response

class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post 
    success_url = '/blog/post-list'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author == request.user:
            success_url = self.get_success_url()
            self.object.delete()
            return redirect(success_url)
        else:
            raise PermissionDenied
        

@login_required
def user_delete(request):
    if request.user.is_authenticated:
        request.user.delete()

        auth_logout(request)

        return redirect('blog_app:about_me')
    

# 태그가 일치하는 글을 함께 출력
def tag_posts(request, slug) : # URL로 전달받은 slug 변수를 아규먼트로 사용
    # 태그가 없는 경우
    if slug == "no-tag" :
        posts = Post.objects.all.filter(tag=None)

    # 태그가 있는 경우
    else :
        tag = Tag.objects.get(slug=slug) # tag를 포함한 Object를 추려냄
        # posts = Post.objects.filter(tag=tag)
    
        # 쿼리 최적화를 위해서 ForeignKey나 일대일 관계로 연결된 테이블 데이터를 미리 가져오는 메서드
        # 한번에 데이터를 저장해놓고 필요할 때 가져다 쓸 수 있습니다.
        posts = Post.objects.filter(tag=tag).select_related('author')
    

    return render(request, 'blog/post_list.html', # 템플릿 재사용
                  {'post_list' : posts})

def create_comment(request, pk) :
    # GET / POST 서로 다른 결과 return
    # 로그인 상태 확인
    if request.user.is_authenticated :
        post = Post.objects.get(pk=pk)
    # POST 리턴 -> Comment 테이블에 값 업데이트
    if request.method == 'POST' :
        comment_form = CommentForm(request.POST) # 작성한 content
        if comment_form.is_valid() :
            comment = comment_form.save(commit=False)
            comment.post = post # 임시 저장상태로 Field로 입력받지 않은 값들을 추가
            comment.author = request.user
            comment.save()

            return redirect(comment.get_absolute_url())
    else :
        raise PermissionDenied

# comment_form.html
class CommentUpdate(LoginRequiredMixin, UpdateView) :
    model = Comment
    form_class = CommentForm
    
    # 로그인한 상태에서 작성자(request.user) 가 object.author(Post.objects.get(pk=pk))과 일치하는지 확인 필요
    def dispatch(self, request, *args, **kwargs): # 방문자가 GET으로 요청했는데 POST로 요청했는지 확인하는 기능
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied # 권한 없는 사람이 글 수정하려 하면 403


def delete_comment(request, pk) : 
    comment = Comment.objects.get(pk=pk) # comment 객체 가져옴
    post = comment.post

    if request.user.is_authenticated and request.user == comment.author :
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied



class CommentDelete(LoginRequiredMixin, DeleteView) :
    model = Comment
    success_url = 'blog'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author == request.user:
            success_url = self.get_success_url()
            self.object.delete()
            return redirect(success_url)
        else:
            raise PermissionDenied
        

fisa_django/blog/templates/blog/about_me.html
{% extends 'blog/base.html' %}
{% load static %}
{% block page_area %}
<!-- Main-->
<div id="main">

    <div class="container px-5" id="one">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-xxl-6">
                <div class="text-center my-5">
                    <h1 class="fw-bolder mb-3">Build things that build things!</h1>
                    <p class="lead fw-normal text-muted mb-4">조진원입니다</p>
                    <a class="btn btn-dark btn-lg" href="#scroll-target">WHO I AM</a>
                </div>
            </div>
        </div>
    </div>

            <!-- About section one-->
            <section class="py-5 bg-light about_me" id="scroll-target">
                <div class="container px-5 my-5"  id="two">
                    <div class="row gx-5 align-items-center">
                        <!-- <div class="col-lg-6"><img class="img-fluid rounded mb-5 mb-lg-0" src="data/spongebob.jpg" alt="..." /></div> -->
                        <div class="col-lg-6 order-first order-lg-last"><img class="img-fluid rounded mb-5 mb-lg-0" src="{% static 'data/spongebob.jpg' %}" alt="..." /></div>
                        <div class="col-lg-6">
                            <h2 class="fw-bolder">Programmer</h2>
                            <p class="lead fw-normal text-muted mb-0">1000번 안 되다가 1번 될 때 느끼는 희열감과<br>
                                내일은 되겠지, 라는 낙천성을 가진 개발자</p>
                        </div>
                    </div>
                </div>
            </section>
            <!-- About section two-->
            <section class="py-5" id="three">
                <div class="container px-5 my-5">
                    <div class="row gx-5 align-items-center">
                        <!-- <div class="col-lg-6 order-first order-lg-last"><img class="img-fluid rounded mb-5 mb-lg-0" src="data/profile.png" alt="..." /></div> -->
                        <div class="col-lg-6 order-first order-lg-last"><img class="img-fluid rounded mb-5 mb-lg-0" src="{% static 'data/profile.png' %}" alt="..." /></div>

                        <div class="col-lg-6">
                            <h2 class="fw-bolder">Technical Editor</h2>
                            <p class="lead fw-normal text-muted mb-0">국어국문학을 전공한 개발자의 눈으로<br> 잘 이해되는 설명과 잘 돌아가는 코드를 가진<br> 책을 세상에 선보이는 지식노동자</p>
                        </div>
                    </div>
                </div>
            </section>

</div>

{% endblock %}

fisa_django/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About 조지넌</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <style>
        /* The navigation bar */
            .navbar {
            overflow: hidden;
            background-color: #333;
            position: fixed; /* Set the navbar to fixed position */
            top: 0; /* Position the navbar at the top of the page */
            width: 100%; /* Full width */
            }
    </style>
</head>
<body>

<!-- Header-->
<div id="header" class="py-5">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <div class="container px-5">
            <a class="navbar-brand">JINWON JO</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog_app:about_me' %}">About me</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog_app:post_list' %}">blog</a></li>
                    <li class="nav-item"><a class="nav-link" href="#three">Technical Editor</a></li>
                </ul>

                {% if user.is_authenticated %}   
                {# 로그인 상태이면 #}
                    {# 본인 ID #}
                    <span class="text-secondary fw-bold"> <a href="{% url 'account_change_password' %}">{{ user.username }} </a> </span>&nbsp;
                    {# 로그아웃 버튼 #}
                    <a class="btn btn-secondary" href="{% url 'account_logout' %}" role="button">로그아웃</a>&nbsp;&nbsp;
                    {# 회원탈퇴 #}
                    <a class="btn btn-secondary" href="{% url 'blog_app:user_delete' %}" role="button">회원탈퇴</a>&nbsp;&nbsp;
                {% else %}
                {# 로그아웃 상태이면 #}
                    {# 로그인 버튼 #}
                    <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#loginModal"><a href="{% url 'account_login' %}">로그인</a>
                    {# 회원 가입 버튼 - 직접 연결해보세요. #}
                    <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#loginModal"><a href="{% url 'account_signup' %}">회원가입</a>
                
                    
                {% endif %}

            </div>
        </div>
    </nav>
</div>

{% block page_area %}

{% endblock %}

<!-- Footer-->
<div id="footer" class="bg-dark py-4 mt-auto fixed-bottom">
    <div class="container px-5">
        <div class="row align-items-center justify-content-between flex-column flex-sm-row">
            <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; YEONJIKIM 2024</div></div>
            <div class="col-auto">
                <span class="text-white mx-1">atangi@naver.com</span>
                <span class="text-white mx-1">&middot;</span>
                <a class="link-light small" href="mailto:atangi@naver.com">Contact</a>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

</body>
</html>

fisa_django/blog/templates/blog/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    정말 삭제하시겠습니까?
    <form method="POST" action="{% url 'blog_app:delete' post.id %}">
        {% csrf_token %}
        <button type="submit">YES</button>
    </form>
</body>
</html>

fisa_django/blog/templates/blog/post_detail.html
{% extends 'blog/base.html'%}
{% load static %}
{% block page_area %}
{% load crispy_forms_tags %}
{% if user.is_authenticated and user == post.author %}
    <a class="btn btn-secondary" href="/blog/edit-post/{{ post.pk }}" role="button">수정</a>&nbsp;&nbsp;          
    <!-- <a class="btn btn-secondary" href="/blog/delete-post/ {{ post.pk }}" role="button">삭제</a>&nbsp;&nbsp;-->
          <!-- Button to open the modal -->
          <a class="btn btn-danger" href="#" role="button" data-bs-toggle="modal" data-bs-target="#deleteModal">삭제</a>&nbsp;&nbsp;

          <!-- The Modal -->
          <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                  <div class="modal-content">
                      <div class="modal-header">
                          <h5 class="modal-title" id="deleteModalLabel">삭제 확인</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                          정말 삭제하시겠습니까?
                      </div>
                      <div class="modal-footer">
                          <form method="POST" action="{% url 'blog_app:delete' post.id %}">
                              {% csrf_token %}
                              <button type="submit" class="btn btn-danger">예</button>
                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">아니오</button>
                          </form>
                      </div>
                  </div>
              </div>
          </div>
{% endif %}
                            <!-- Post content-->
                            <article>
                                <!-- Post header-->
                                <header class="mb-4">
                                    <!-- Post title-->
                                    <h1 class="fw-bolder mb-1">{{ post.title }}</h1>
                                    <!-- Post meta content-->
                                    <div class="text-muted fst-italic mb-2">{{ post.created_at }}</div>
                                    <!-- Post categories-- tag가 있는 글이면 tag를 호출-->
                                    {% if post.tag.exists %}
                                        {% for tag in post.tag.all %}
                                            <a class="badge bg-secondary text-decoration-none link-light" href="{{ tag.get_absolute_url }}">{{tag.tag_name}} {{ tag.post_set.count }}</a>
                                        {% endfor %}
                                    {% endif %}
                                    <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                                    <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>


                                </header>
                                <!-- Preview image figure-->
                                {% if post.header_img %}
                                <figure class="mb-4">
                                    <img class="img-fluid rounded" src="{{ post.header_img.url }}" alt="..." /></figure>
                                {% endif %}
                                    <!-- Post content-->
                                <section class="mb-5">
                                    <p class="fs-5 mb-4"> {{ post.content }}</p>
                                    {% if post.file_upload %}
                                    <a href="{{ post.file_upload.url }}" class="btn btn-dark">다운로드</a>
                                    {% endif %}
                                </section>
                                <section>
                                    <div class="card bg-light"> 
                                        <div class="card-body" id="comment-area">
                                        <!-- Comments Form -->
                                        <div class="card my-4">
                                            <h5 class="card-header">댓글</h5>
                                            <div class="card-body">
                                                {% if user.is_authenticated %}
                                                    <form id="comment-form" method="POST" action="{{ post.get_absolute_url }}/create-comment">
                                                        {% csrf_token %}
                                                        <div class="form-group">
                                                            {{ comment_form | crispy }}
                                                        </div>
                                                        <button type="submit" class="btn btn-dark">등록</button>
                                                    </form>
                                                {% else %}
                                                    <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="#" data-toggle="modal" data-target="#loginModal">Log in and leave a comment</a>
                                                {% endif %}
                                            </div>
                                        </div>
                                
                                        {% if post.comment_set.exists %}
                                            {% for comment in post.comment_set.iterator %}
                                                <!-- Single Comment -->
                                                <div class="d-flex align-items-center" id="comment-{{ comment.pk }}">
                                                    <div class="flex-grow-1 ms-3">
                                                        {% if user.is_authenticated and comment.author == user %}
                                                            <div class="float-right">
                                                                <a role="button"
                                                                   class="btn btn-sm btn-secondary"
                                                                   id="comment-{{ comment.pk }}-update-btn"
                                                                   href="/blog/update-comment/{{ comment.pk }}">
                                                                    수정
                                                                </a>
                                                                <a role="button"
                                                                   href="#"
                                                                   id="comment-{{ comment.pk }}-delete-modal-btn"
                                                                   class="btn btn-sm btn-danger"
                                                                   data-bs-toggle="modal" data-bs-target="#deleteCommentModal-{{ comment.pk }}">
                                                                    삭제
                                                                </a>
                                                            </div>
                                
                                                            <!-- Modal -->
                                                            <div class="modal fade" id="deleteCommentModal-{{ comment.pk }}" tabindex="-1" role="dialog" aria-labelledby="deleteCommentModalLabel" aria-hidden="true">
                                                                <div class="modal-dialog" role="document">
                                                                    <div class="modal-content">
                                                                        <div class="modal-header">
                                                                            <h5 class="modal-title" id="deleteCommentModalLabel">정말 삭제하나요?</h5>
                                                                            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                                                                                <span aria-hidden="true">&times;</span>
                                                                            </button>
                                                                        </div>
                                                                        <div class="modal-body">
                                                                            <del>{{ comment | linebreaks }}</del>
                                                                        </div>
                                                                        <div class="modal-footer">
                                                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                                                                            <a role="button" class="btn btn-danger" href="/blog/delete-comment/{{ comment.pk }}">삭제</a>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                
                                                        {% endif %}
                                                        <h5 class="mt-0">
                                                            {{ comment.author.username }}
                                                            &nbsp;&nbsp;<small class="text-muted">{{ comment.created_at }}</small>
                                                        </h5>
                                                        <p>{{ comment.content | linebreaks }}</p>
                                                        {% if comment.created_at != comment.modified_at %}
                                                            <p class="text-muted float-right"><small>Updated: {{ comment.updated_at }}</small></p>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                            </section>

                            </article>
{% endblock %}